### ISSUE TITLE
Organisation

### ISSUE THREAD

**Issue by greut** [HE-Arc/Finance_Cloud#21]
Cher Finance Cloud.

@Rocla étant une personne super active, vous risquez de le voir abattre une masse de travail sans avoir l'opportunité de pouvoir sauter dans le train désormais en marche.

Quelques recommendations:
1. Ayez des tickets qui puissent être _actionnable_. En le lisant, on devrait savoir ce qu'il y a à faire et surtout quand c'est terminé. Évitez les choses subjectives tel que _make it sexy_.
2. Assignez-vous des tâches et engagez-vous à les réaliser (avant une échéance à définir, e.g. milestone)
3. Dans la mesure du possible, ne travaillez que sur une tâche à la fois.
4. (Optionel) quand une tâche vous parait terminée, créez un pull request et demandez à un de vos collègues de la tester.

À éviter à tout prix!
1. Un seul membre écrit des tâches. Solution, retrouvez-vous autour d'une table et mettez en commun vos objectifs. Il est important que tout le monde partage la même vision.
2. Une personne assigne des tâches à d'autres. Solution, en tant qu'adulte, vous décidez quelles tâches vous motivent et ainsi vous vous engagez à les faire.
3. Le travail d'un membre pénalise les autres membres du groupe. Solution, travaillez dans une branche qui ne sera mergée dans master via un pull request.

**Comment by RomainClaret** [comment]
@fabioman @matbandeli Petit flood pour vous rappeler
https://github.com/HE-Arc/Finance_Cloud/milestones
https://github.com/HE-Arc/Finance_Cloud/issues
