### ISSUE TITLE
Erreur 500

### ISSUE THREAD

**Issue by greut** [HE-Arc/Finance_Cloud#3]
Vos logs

```
Puma starting in single mode...
 * Version 2.15.3 (ruby 2.2.3-p173), codename: Autumn Arbor Airbrush
 * Min threads: 0, max threads: 16
 * Environment: production
 ! Unable to load application: LoadError: cannot load such file -- rails/all
 /var/www/config/application.rb:3:in `require': cannot load such file -- rails/all (LoadError)
...
```

Regardez vos fichiers de config:

```
/var/www/config/nginx.conf
/var/www/config/puma.rb
# dans le pire des cas.
/etc/services/puma/run
```

Et j'ai stoppé puma car c'est inutile qu'il remplisse les logs de la machine.

``` console
$ sudo sv start puma
```

Ce qui est dans le README a été testé et est sensé fonctionner. Si vous voulez faire autrement, c'est à vos risques et périls.

**Comment by RomainClaret** [comment]
Je veux bien faire selon le README, cependant je n'arrive pas à faire le lien avec le clone de notre repertoire git pour la configuration. Je vois dans le README un setup avec une application créé directement sur le serveur `rails new app`.

**Comment by greut** [comment]
Il faut que les chemins jouent la moindre.

Il faut donner à puma le chemin de l'application (répertoire contenant le `Gemfile` et `config.ru`) et à nginx le chemin du répertoire `public`.

**Comment by RomainClaret** [comment]
Oh ma gad... J'ai à nouveau tout pété... J'ai vraiment la poisse avec ce déploiement u_u
<img width="578" alt="screen shot 2016-02-15 at 21 10 53" src="https://cloud.githubusercontent.com/assets/8895475/13059170/aab3c4d0-d428-11e5-9774-afaeb9735293.png">

**Comment by greut** [comment]
Bizarre, les gems n'ont pas été installées.

``` console
$ gem install bundler rails rack rake puma
$ bundler --version
Bundler version 1.11.2
```

Croisons les doigts ;-)

**Comment by RomainClaret** [comment]
Tout ça ne devrait plus être d'actualité dés à présent :) 3c33db5f3d61c6869c008720c2ad650e094c2aff
