### ISSUE TITLE
Login & Sign up

### ISSUE THREAD

**Issue by RomainClaret** [HE-Arc/Finance_Cloud#4]
- [x] model -> user (username, email, password, question?, answer?)
- [x] controller -> create, view
- [x] view -> basic
- [x] Add to navigation bar (signup, view profile, edit profile)
- [x] Login

**Comment by greut** [comment]
Pistes : devise, cancan, etc.

**Comment by RomainClaret** [comment]
36c0438d2656b0bec377e7fd74443e597931b465
8059bee21cb20ca149670283eaf50a7b9f9270bb
ddd5af201b5bffdca1a8451b2db26f9b0cdba2f2

**Comment by RomainClaret** [comment]
4430719319509a2a5a3ff9a7fc76395305f2b76b
2705a77c29a59f72fe1b76d614b5094456fab7c6

Travis is happy as well [![Build Status](https://travis-ci.org/HE-Arc/Finance_Cloud.svg?branch=add-authentication)](https://travis-ci.org/HE-Arc/Finance_Cloud)

Making a pull request on this now :)

**Comment by RomainClaret** [comment]
#23
